RBENV_PATH="/usr/local/opt/rbenv"

export PATH="$RBENV_PATH/bin:$RBENV_PATH/shims:$PATH"
eval "$(rbenv init -)"

export RUBY_HEAP_FREE_MIN=100000
export RUBY_GC_HEAP_INIT_SLOTS=600000
export RUBY_HEAP_SLOTS_INCREMENT=300000
export RUBY_GC_MALLOC_LIMIT=50000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
