add_newline = false
palette = "catppuccin_mocha"

[aws]
disabled = false
format = '[$symbol($profile )(\($region\) )]($style)'
style = 'bold yellow'
symbol = " "

[aws.region_aliases]
us-east-1 = 'va'
us-east-2 = 'oh'
us-west-1 = 'ca'
us-west-2 = "or"

[battery]
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'
vimcmd_symbol = '[V](bold green)'

[cmake]
disabled = true

[directory]
disabled = true
read_only = '🔒'
read_only_style = 'red'

[docker_context]
format = '[$symbol$context]($style) '

[dotnet]
# Remove project.json to avoid showing for Nx projects
detect_files = [
  'global.json',
  'Directory.Build.props',
  'Directory.Build.targets',
  'Packages.props',
]

[gcloud]
disabled = true
format = '[$symbol$account(@$domain)(\($region\))]($style) '
style = 'bold blue'
symbol = " "

[gcloud.region_aliases]
us-central1 = 'ia'
us-east1 = 'sc'
us-east4 = 'va'
us-east5 = 'oh'
us-south1 = 'tx'
us-west1 = 'or'
us-west2 = 'ca'
us-west3 = 'ut'
us-west4 = 'nv'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " "

[git_commit]
commit_hash_length = 7
only_detached = true
style = 'bold green'
tag_disabled = true

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '

[git_status]
disabled = false

[golang]
format = '[$symbol($version )]($style)'
style = 'bold cyan'
symbol = " "

[helm]
format = '[$symbol($version )]($style)'

[hostname]
disabled = true

[kubernetes]
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]
detect_files = ['Tiltfile']
format = '[󱃾 $context \($namespace\)]($style) '
style = 'bold blue'

[nats]
disabled = true
format = '[$symbol$name]($style)'
style = 'bold purple'
symbol = '✉️ '

[nix_shell]
disabled = false
format = '[$symbol$name]($style)'
style = 'bold blue'
symbol = '❄️ '

[nodejs]
format = '[$symbol($version )]($style)'
style = 'bold green'
symbol = '󰎙 '

[package]
disabled = false
format = '[$symbol$version]($style) '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[pulumi]
disabled = false
format = '[$symbol($username@)$stack]($style) '
style = 'bold 5'
symbol = ' '

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'bold yellow'
symbol = ' '

[rust]
disabled = false
format = '[$symbol($version )]($style)'
style = 'bold red'
symbol = ' '

[shell]
disabled = false
format = '[$indicator]($style) '
style = 'white bold'
fish_indicator = '󰈺 '
nu_indicator = 'nu'
zsh_indicator = 'zsh'

[terraform]
format = '[$symbol$workspace]($style) '
symbol = '󱁢 '

[time]
disabled = true
format = '[\[$time\]]($style) '
style = 'bold yellow'
time_format = '%T'
utc_time_offset = 'local'

[vagrant]
disabled = false
format = '[$symbol($version )]($style)'
style = 'cyan bold'
symbol = '⍱ '
