#!/usr/bin/env zsh
alias brews='brew list -1'
alias csvcols="cut -d, -f"
alias ln="ln -v"
alias mkdir="mkdir -p"
alias mux="tmuxinator"
alias psgrep="ps -ax | grep"
alias sshgen="ssh-keygen -m PEM -t rsa -C"
alias strace="dtruss"
alias tmux="tmux -2"

# Git
alias gcl="git clone"
alias ggpl="ggpull"
alias ggpsh="ggpush"
alias ggpshf="ggpush --force-with-lease"
alias gm="git merge"
alias gom="git merge --no-ff --no-edit"
alias grb="git rebase"
alias gbd="git branch -D"
alias gpr="git pull-request"
alias gdpr="git difftool origin/master...origin/$(current_branch)"

# Docker
alias di="docker images"
alias db="docker build"
alias dr="docker run -it --rm"
alias dt="docker tag"
alias dp="docker push"
alias dcb="docker compose build"
alias dcu="docker compose up"
alias dcr="docker compose run --rm"

# Go
alias got="go test ./... -v"

# Kubernetes
alias kc="kubectl"

# Ollama
alias ol="ollama run llama3.2:3b"

# Python
alias python="python3"
alias py="python"
alias py3="python3"
alias pip="pip3"
alias pir="pip install -r requirements.txt"
alias pif="pip freeze > requirements.txt"
alias pv="virtualenv env"
alias pva="source ./env/bin/activate"
alias pvd="deactivate"

# tmux
alias tm="tmuxinator"
