#!/usr/bin/env zsh
alias brews='brew list -1'
alias csvcols="cut -d, -f"
alias ln="ln -v"
alias mkdir="mkdir -p"
alias psgrep="ps -ax | grep"
alias r="/usr/bin/r"
alias rd="rm -rf"
alias tmux="tmux -2"
alias strace="dtruss"

alias extest="py.test -x --ff --pep8"

# Git
alias git="hub"
alias gcl="git clone"
alias ggpl="ggpull"
alias ggpsh="ggpush"
alias gm="git merge"
alias gom="git merge --no-ff --no-edit"
alias grb="git rebase"
alias gbd="git branch -D"
alias gpr="git pull-request"
alias gdpr="git difftool origin/master...origin/$(current_branch)"
alias gt="gittower"
alias gts="gittower --status"

# Docker
alias di="docker images"
alias db="docker build"
alias dr="docker run -it --rm"
alias dt="docker tag"
alias dp="docker push"
alias dm="docker-machine"
alias dmc="docker-machine create"
alias dcb="docker-compose build"
alias dcu="docker-compose up -d"
alias dcr="docker-compose run --rm"

# Python
alias py="python"
alias py3="python3"
alias pi="pip install -r requirements.txt"
alias pf="pip freeze > requirements.txt"
alias pv="virtualenv env"
alias pva="source ./env/bin/activate"
alias pvd="deactivate"

# Django
alias djp="django-admin.py startproject"
alias dja="python manage.py startapp"
alias djs="python manage.py runserver"
alias djc="python manage.py shell"
alias djdbc="python manage.py makemigrations"
alias djdbm="python manage.py migrate"

# Ruby
alias rb="ruby"
alias rk="bundle exec rake"
alias gi="gem install"
alias giv="gem install -v"
alias s="spring rspec && testscomplete"
alias rps="bundle exec rake parallel:spec && testscomplete"
alias rtest="bundle exec ruby -Itest && testscomplete"
alias t="rtest && testscomplete"
alias f="foreman start"

# Bundler
alias b="bundle"
alias be="bundle exec"
alias bi="bundle install"
alias bl="bundle list"
alias bp="bundle package"
alias bu="bundle update"

# Rails
alias rc="bundle exec rails console"
alias rg="bundle exec rails generate"
alias rdbm="bundle exec rake db:migrate"
alias rdbr="bundle exec rake db:rollback STEP="
alias ap="bundle exec rake assets:precompile RAILS_ENV=production"

# Elixir
alias e="elixir"

# Mix
alias m="mix"
alias mi="mix deps.get"
alias mt="mix test"

# Phoenix
alias pxn="mix phoenix.new"
alias pxdbc="mix ecto.create"
alias pxdbm="mix ecto.migrate"
alias pxgj="mix phoenix.gen.json"
alias pxgm="mix phoenix.gen.model"
alias pxgc="mix phoenix.gen.channel"
alias pxs="mix phoenix.server"
alias pxsi="iex -S mix phoenix.server"
alias pxr="mix phoenix.routes"

# PostgreSQL
alias pgstart="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias pgstop="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop -m fast"
