#!/usr/bin/env zsh

# Perform an ls -la after switching directories, because I'm going to do it.
function cd {
  builtin cd "$@" && ls -la;
}

# Count the total number of lines in files containing the given extension
# $1 - File extension
function count-lines () {
  find . -name "*.$1" | xargs wc -l;
}

# Clear duplicates from the "Open With" menu in OS X.
function clear-open-with-dups () {
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
}

# Remove Docker images in the "dangling" state
function clean-docker () {
  docker system prune -a --volumes
  docker rm `docker ps --no-trunc -aq`
  docker images -q --filter "dangling=true" | xargs docker rmi
}

# Remove Podman images in the "dangling" state
function clean-podman () {
  podman rm `podman ps --no-trunc -aq`
  podman images -q --filter "dangling=true" | xargs podman rmi
}

# Clear the cache to fix the iOS Simulator
function fix-ios-sim () {
  rm -rf ~/Library/Developer/CoreSimulator/Caches
}

# Flush the DNS cache in macOS
function flush-dns () {
  sudo dscacheutil -flushcache
  sudo killall -HUP mDNSResponder
}

# Kill all processes using the given directory
# $1 - String representing the directory
function kill-dir () {
  lsof | grep $1 | awk '{print $2}' | xargs kill;
}

# Display man pages in vim for syntax highlighting.
function man() {
  /usr/bin/man $* | \
      col -b | \
        vim -R -c 'set ft=man nomod nolist' -
}

# Make a directory and change to it
function mcd () {
  mkdir -p "$@" && eval cd "\"\$$#\"";
}

# Scan the network for devices
function netscan () {
  ifconfig | grep broadcast; arp -a | grep :
}

# Remove vim undo files from the current directory
function rmpyc () {
  find . -name "*.pyc" -exec rm -f {} \;
}

# Remove vim undo files from the current directory
function rmundo () {
  find . -name "*.un~" -exec rm -f {} \;
}

# Monitor the TCP traffic on the specified port
# $1 - Integer representing the TCP port to be monitored
function tcpmonitor () {
  sudo /usr/sbin/tcpdump -ln -A -s1024 -i $1 tcp port $2;
}

# Remove vim plugins not included in vimrc
function vim-clean () {
  vim -c "execute \"PlugClean!\" | q | q"
}

# Update vim plugins
function vim-update () {
  vim +PlugUpdate +qall
}

# Update oh-my-zsh
function zsh-update () {
  pushd "$HOME/.oh-my-zsh"
    git pull origin master
  popd
}
