vim.filetype.add({
  extension = {
    gotmpl = "gotmpl",
    hujson = "jsonc",
    mdx = "markdown.mdx",
    tfvars = "terraform-vars",
    tmux = "sh",
  },
  filename = {
    [".curlrc"] = "sh",
    [".gitlab-ci.yml"] = "yaml.gitlab",
    [".inputrc"] = "sh",
    ["Chart.lock"] = "helm",
    ["Chart.yaml"] = "helm",
    ["go.work"] = "gowork",
    ["skhdrc"] = "sh",
    ["tmux.conf"] = "sh",
  },
  pattern = {
    [".*%.env%..*"] = "sh",
    [".*docker%-compose[^/]*%.ya?ml"] = "yaml.docker-compose",
    [".*%.tfvars%.json"] = "terraform-vars",
    [".*/%.config/waybar/.*/config"] = "jsonc",
    [".*/%.vscode/.*%.json"] = "jsonc",
    [".*/%.zed/.*%.json"] = "jsonc",
    [".*/Dockerfile.*"] = "dockerfile",
    [".*/helmfile%.d/.*%.ya?ml"] = "helm",
    [".*/hypr/.*%.conf"] = "dosini",
    [".*/templates/.*%.tpl"] = "helm",
    [".*/templates/.*%.ya?ml"] = "helm",
    [".*/values[^/]*%.ya?ml"] = "yaml.helm-values",
  },
})
