# https://espanso.org/docs/

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json

# Enable config auto-reload after a file change is detected.
auto_restart: true

# Espanso supports multiple ways of injecting text into applications. Each of
# them has its quirks, therefore you may want to change it if you are having problems.
# By default, espanso uses the "Auto" backend which should work well in most cases,
# but you may want to try the "Clipboard" or "Inject" backend in case of issues.
backend: auto

# Use the clipboard if the text is longer than 'clipboard_threshold' characters.
clipboard_threshold: 100

# Set the search shortcut
search_shortcut: ALT+SHIFT+SPACE

# Show the icon in the menu bar
show_icon: true

# Customize the key used to disable and enable espanso (when double tapped)
toggle_key: OFF
